// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fluxbveksncgypofvmdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdXhidmVrc25jZ3lwb2Z2bWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTAzNjksImV4cCI6MjA2OTE2NjM2OX0.n6KFPIFBIAZJUKe9soMjpSQypakFY9lAtqKxSf5AHf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});